/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlns;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Nhansu extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    /**
     * Creates new form Nhansu
     */
    public Nhansu() {
        initComponents();
        conn = QLNS.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btntimkiem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbtrangchu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangnhansu = new javax.swing.JTable();
        btndanhdachnhansu = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Bảng thống kê nhân sự");

        txttimkiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("Tìm kiếm nhân sự:");

        btntimkiem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btntimkiem.setText("Tìm kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btntimkiem))
                    .addComponent(jLabel6))
                .addContainerGap(536, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btntimkiem)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nhân sự");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tin nhắn");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Đăng xuất");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Doanh thu");

        lbtrangchu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbtrangchu.setForeground(new java.awt.Color(255, 255, 255));
        lbtrangchu.setText("Trang chủ");
        lbtrangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbtrangchuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbtrangchu)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(jLabel5)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbtrangchu)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(30, 30, 30))
        );

        bangnhansu.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        bangnhansu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên dăng nhập:", "Mật khẩu:", "Họ ", "Tên", "Chức vụ"
            }
        ));
        jScrollPane1.setViewportView(bangnhansu);

        btndanhdachnhansu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btndanhdachnhansu.setText("Danh sách nhân sự");
        btndanhdachnhansu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndanhdachnhansuMouseClicked(evt);
            }
        });
        btndanhdachnhansu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndanhdachnhansuActionPerformed(evt);
            }
        });

        btnsua.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnxoa.setText("Xoá");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btndanhdachnhansu)
                                .addGap(98, 98, 98)
                                .addComponent(btnsua)
                                .addGap(51, 51, 51)
                                .addComponent(btnxoa)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndanhdachnhansu)
                    .addComponent(btnsua)
                    .addComponent(btnxoa))
                .addGap(17, 17, 17))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        // Hiển thị hộp thoại xác nhận trước khi đăng xuất
        int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn đăng xuất khỏi tài khoản  không?", "Xác nhận đăng xuất", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            // Nếu người dùng chọn "Yes" (Đồng ý)
            Dangnhap dangnhap = new Dangnhap();
            dangnhap.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void lbtrangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtrangchuMouseClicked
        // TODO add your handling code here:
        Trangchu trangchu = new Trangchu();
            trangchu.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_lbtrangchuMouseClicked

    private void btndanhdachnhansuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndanhdachnhansuMouseClicked
       String sql = "SELECT `tendangnhap`, `matkhau`, `ho`, `ten`, `banla` FROM `nguoidung`";

    try {
        ps = conn.prepareStatement(sql);
        rs = ps.executeQuery();

        // Xóa toàn bộ dữ liệu trong bảng bangnhansu trước khi hiển thị mới
        DefaultTableModel model = (DefaultTableModel) bangnhansu.getModel();
        model.setRowCount(0);

        // Hiển thị từng dòng dữ liệu lấy từ cơ sở dữ liệu lên bảng
        while (rs.next()) {
            String tendangnhap = rs.getString("tendangnhap");
            String matkhau = rs.getString("matkhau");
            String ho = rs.getString("ho");
            String ten = rs.getString("ten");
            String banla = rs.getString("banla");

            // Thêm dòng dữ liệu vào bảng
            model.addRow(new Object[]{tendangnhap, matkhau, ho, ten, banla});
        }
    } catch (SQLException ex) {
        Logger.getLogger(dangky.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_btndanhdachnhansuMouseClicked

    private void btndanhdachnhansuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndanhdachnhansuActionPerformed
      
    }//GEN-LAST:event_btndanhdachnhansuActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
     int selectedRow = bangnhansu.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng để sửa!");
        return;
    }

    // Lưu lại giá trị ban đầu của các ô cần sửa
    String tendangnhap = bangnhansu.getValueAt(selectedRow, 0).toString();
    String matkhau = bangnhansu.getValueAt(selectedRow, 1).toString();
    String ho = bangnhansu.getValueAt(selectedRow, 2).toString();
    String ten = bangnhansu.getValueAt(selectedRow, 3).toString();
    String banla = bangnhansu.getValueAt(selectedRow, 4).toString();

    // Hiển thị thông báo và nhập giá trị mới cho từng ô cần sửa
    String tendangnhapMoi = JOptionPane.showInputDialog(this, "Nhập tên đăng nhập mới:", tendangnhap);
    if (tendangnhapMoi == null) {
        // Người dùng bấm Cancel, không thực hiện sửa đổi
        return;
    }

    String matkhauMoi = JOptionPane.showInputDialog(this, "Nhập mật khẩu mới:", matkhau);
    if (matkhauMoi == null) {
        return;
    }

    String hoMoi = JOptionPane.showInputDialog(this, "Nhập họ mới:", ho);
    if (hoMoi == null) {
        return;
    }

    String tenMoi = JOptionPane.showInputDialog(this, "Nhập tên mới:", ten);
    if (tenMoi == null) {
        return;
    }

    // Show a dialog for selecting "banla" value
    String[] banlaOptions = {"Nhân viên", "Manager"}; // Replace with actual options
    String banlaMoi = (String) JOptionPane.showInputDialog(this, "Chọn banla mới:", "Chọn", JOptionPane.PLAIN_MESSAGE, null, banlaOptions, banla);
    if (banlaMoi == null) {
        return;
    }

    // Thực hiện cập nhật dữ liệu vào cơ sở dữ liệu XAMPP
    try {
        String sql = "UPDATE `nguoidung` SET `tendangnhap`=?, `matkhau`=?, `ho`=?, `ten`=?, `banla`=? WHERE `tendangnhap`=?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, tendangnhapMoi);
        ps.setString(2, matkhauMoi);
        ps.setString(3, hoMoi);
        ps.setString(4, tenMoi);
        ps.setString(5, banlaMoi);
        ps.setString(6, tendangnhap);

        int rowsAffected = ps.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Đã cập nhật thông tin thành công!");
            // Sau khi cập nhật thành công, cần cập nhật lại dữ liệu trên bảng
            btndanhdachnhansuMouseClicked(null);
        } else {
            JOptionPane.showMessageDialog(null, "Không thành công. Lỗi khi cập nhật dữ liệu!");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Lỗi khi cập nhật dữ liệu vào cơ sở dữ liệu!");
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
         int selectedRow = bangnhansu.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng để xoá!");
        return;
    }

    // Lấy giá trị của cột "Tên đăng nhập" trong dòng đã chọn
    String tendangnhap = bangnhansu.getValueAt(selectedRow, 0).toString();

    // Xác nhận xoá dòng và thông báo cho người dùng
    int option = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xoá dòng này?", "Xác nhận xoá", JOptionPane.YES_NO_OPTION);
    if (option == JOptionPane.YES_OPTION) {
        // Thực hiện xoá dòng khỏi cơ sở dữ liệu XAMPP
        try {
            String sql = "DELETE FROM `nguoidung` WHERE `tendangnhap`=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, tendangnhap);

            int rowsAffected = ps.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Đã xoá dòng thành công!");
                // Sau khi xoá thành công, cần cập nhật lại dữ liệu trên bảng
                btndanhdachnhansuMouseClicked(null);
            } else {
                JOptionPane.showMessageDialog(null, "Không thành công. Lỗi khi xoá dữ liệu!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Lỗi khi xoá dữ liệu từ cơ sở dữ liệu!");
            ex.printStackTrace();
        }
    }
    }//GEN-LAST:event_btnxoaActionPerformed
    
    
    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
       String keyword = txttimkiem.getText();
    if (keyword.trim().isEmpty()) {
        // Người dùng không nhập từ khóa tìm kiếm, không thực hiện tìm kiếm
        return;
    }

    // Thực hiện truy vấn đến cơ sở dữ liệu để tìm kiếm các bản ghi phù hợp
    try {
        String sql = "SELECT * FROM `nguoidung` WHERE `tendangnhap` LIKE ? OR `ho` LIKE ? OR `ten` LIKE ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, "%" + keyword + "%");
        ps.setString(2, "%" + keyword + "%");
        ps.setString(3, "%" + keyword + "%");
        ResultSet rs = ps.executeQuery();

        // Tạo DefaultTableModel để hiển thị dữ liệu trên bảng bangnhansu
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tên đăng nhập");
        model.addColumn("Mật khẩu");
        model.addColumn("Họ");
        model.addColumn("Tên");
        model.addColumn("Chức vụ");

        while (rs.next()) {
            // Lấy thông tin từ ResultSet và thêm vào bảng
            String tendangnhap = rs.getString("tendangnhap");
            String matkhau = rs.getString("matkhau");
            String ho = rs.getString("ho");
            String ten = rs.getString("ten");
            String banla = rs.getString("banla");

            model.addRow(new Object[]{tendangnhap, matkhau, ho, ten, banla});
        }

        // Đóng kết nối và giải phóng tài nguyên
        rs.close();
        ps.close();

        // Set model cho bảng bangnhansu
        bangnhansu.setModel(model);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Lỗi khi tìm kiếm dữ liệu trong cơ sở dữ liệu!");
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btntimkiemActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nhansu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nhansu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nhansu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nhansu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nhansu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangnhansu;
    private javax.swing.JButton btndanhdachnhansu;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbtrangchu;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
